import { db, logActivity } from "./db";
import type { User } from "./auth";
import { emptyState, esc, formVals, inlineConfirm, layout, opt, redirect } from "./web";
import { inventoryImport,inventoryImportPage,inventoryImportTemplate,namedId,nonnegativeInt,numberValue,textValue,type ImportConfig } from "./csv";
const importConfig:ImportConfig={entity:"component",path:"components",columns:[{header:"name",db:"name",value:textValue,default:""},{header:"category",db:"category_id",value:x=>namedId("categories",x),default:null},{header:"location",db:"location_id",value:x=>namedId("locations",x),default:null},{header:"qty",db:"qty",value:nonnegativeInt,default:0},{header:"min_qty",db:"min_qty",value:nonnegativeInt,default:0},{header:"cost",db:"cost",value:numberValue,default:null},{header:"serial",db:"serial",value:textValue,default:null},{header:"notes",db:"notes",value:textValue,default:null}]};

function form(c: any = {}): string {
  const cats = db.query("SELECT id,name FROM categories WHERE ctype='component' ORDER BY name").all() as any[];
  const locs = db.query("SELECT id,name FROM locations ORDER BY name").all() as any[];
  return `<div class="frm"><div><label>Name *</label><input name="name" value="${esc(c.name || "")}" required></div>
<div><label>Category</label><select name="category_id"><option value="">—</option>${opt(cats,c.category_id)}</select></div><div><label>Location</label><select name="location_id"><option value="">—</option>${opt(locs,c.location_id)}</select></div>
<div><label>Total quantity</label><input type="number" min="0" name="qty" value="${esc(c.qty ?? 0)}"></div><div><label>Min. available</label><input type="number" min="0" name="min_qty" value="${esc(c.min_qty ?? 0)}"></div>
<div><label>Unit cost</label><input type="number" step="0.01" name="cost" value="${esc(c.cost || "")}"></div><div><label>Serial</label><input name="serial" value="${esc(c.serial || "")}"></div></div>
<div style="margin-bottom:14px"><label>Notes</label><textarea name="notes">${esc(c.notes || "")}</textarea></div>`;
}
function vals(v:(k:string)=>string):any[]{const n=(k:string)=>v(k)||null;return [v("name"),n("category_id"),Math.max(0,Number(v("qty"))||0),Math.max(0,Number(v("min_qty"))||0),n("location_id"),n("cost"),n("serial"),n("notes")];}
function stockStats(total:any,left:any):string{const t=Number(total||0),l=Number(left||0),u=Math.max(0,t-l);return `<div class="stats"><div class="stat"><div class="n">${t}</div><div class="l">Total</div></div><div class="stat"><div class="n">${u}</div><div class="l">Used</div></div><div class="stat"><div class="n">${l}</div><div class="l">Left</div></div></div>`;}
export function list(user:User,url:URL,canEdit:boolean):Response{const rows=db.query(`SELECT c.*,cat.name category,l.name location,c.qty-COALESCE((SELECT SUM(qty) FROM component_assets x WHERE x.component_id=c.id),0) available FROM components c LEFT JOIN categories cat ON cat.id=c.category_id LEFT JOIN locations l ON l.id=c.location_id ORDER BY c.name`).all() as any[];return layout(user,"Components",`<h1>Components <span class="muted">(${rows.length})</span></h1><div class="toolbar">${canEdit?'<a class="btn" href="/components/new">+ New component</a> <a class="btn sec" href="/components/import">Import CSV</a>':""}</div>${rows.length===0?emptyState("No components found","Create your first component to start tracking installed parts.",canEdit?'<a class="btn" href="/components/new">+ New component</a>':""):`<div class="card table-wrap" style="padding:0"><table class="sticky-table"><tr><th>Name</th><th>Category</th><th>Location</th><th>Total</th><th>Used</th><th>Left</th></tr>${rows.map(c=>`<tr data-href="/components/${c.id}"><td><a href="/components/${c.id}">${esc(c.name)}</a></td><td>${esc(c.category||"")}</td><td>${esc(c.location||"")}</td><td>${c.qty}</td><td>${Math.max(0,Number(c.qty)-Number(c.available))}</td><td>${c.available}${c.available<=c.min_qty?' <span class="badge b-red">low</span>':""}</td></tr>`).join("")}</table></div>`}`,"/components",url.searchParams.get("m")||"");}
export function newPage(user:User):Response{return layout(user,"New component",`<h1>New component</h1><div class="card"><form method="post" action="/components">${form()}<button class="btn">Create</button></form></div>`,"/components");}
export async function create(user:User,req:Request):Promise<Response>{const v=await formVals(req);const r=db.run("INSERT INTO components(name,category_id,qty,min_qty,location_id,cost,serial,notes) VALUES(?,?,?,?,?,?,?,?)",vals(v));logActivity(user.id,"create","component",Number(r.lastInsertRowid),v("name"));return redirect(`/components/${r.lastInsertRowid}?m=Component created`);}
export function detail(user:User,id:string,url:URL,canEdit:boolean):Response{const c=db.query(`SELECT c.*,cat.name category,l.name location,c.qty-COALESCE((SELECT SUM(qty) FROM component_assets x WHERE x.component_id=c.id),0) available FROM components c LEFT JOIN categories cat ON cat.id=c.category_id LEFT JOIN locations l ON l.id=c.location_id WHERE c.id=?`).get(id) as any;if(!c)return layout(user,"Not found","<h1>Component not found</h1>","/components");const installed=db.query("SELECT x.id,x.qty,x.at,a.id asset_id,a.asset_tag FROM component_assets x JOIN assets a ON a.id=x.asset_id WHERE x.component_id=? ORDER BY a.asset_tag").all(id) as any[];const assets=db.query("SELECT id,asset_tag name FROM assets WHERE status!='archived' ORDER BY asset_tag").all() as any[];return layout(user,c.name,`<h1>${esc(c.name)}</h1>${stockStats(c.qty,c.available)}<div class="card"><table><tr><th>Category</th><td>${esc(c.category||"")}</td></tr><tr><th>Location</th><td>${esc(c.location||"")}</td></tr><tr><th>Serial</th><td>${esc(c.serial||"")}</td></tr><tr><th>Notes</th><td>${esc(c.notes||"")}</td></tr></table></div>${canEdit?`<div class="card">${c.available>0?`<form method="post" action="/components/${esc(id)}/install" style="display:flex;gap:8px;align-items:end"><div style="flex:1"><label>Asset</label><select name="asset_id" required><option value="">Select asset…</option>${opt(assets,"")}</select></div><div><label>Quantity</label><input type="number" min="1" max="${c.available}" name="qty" value="1"></div><button class="btn">Install</button></form>`:'<span class="badge b-red">No units available</span>'}<div style="margin-top:12px"><a class="btn sec sm" href="/components/${esc(id)}/edit">Edit</a> ${inlineConfirm(`component-${id}`,`/components/${id}/delete`,"Delete component","Delete this component?",user.csrfToken)}</div></div>`:""}<h2>Installed in assets</h2><div class="card table-wrap" style="padding:0"><table class="sticky-table"><tr><th>Asset</th><th>Quantity</th><th>Installed</th><th></th></tr>${installed.map(x=>`<tr><td><a href="/assets/${x.asset_id}">${esc(x.asset_tag)}</a></td><td>${x.qty}</td><td>${esc(x.at)}</td><td>${canEdit?`<form class="inline" method="post" action="/components/${esc(id)}/remove/${x.id}"><input type="number" min="1" max="${x.qty}" name="qty" value="1" style="width:65px"><button class="btn sec sm">Remove</button></form>`:""}</td></tr>`).join("")}</table></div>`,"/components",url.searchParams.get("m")||"");}
export function editPage(user:User,id:string):Response{const c=db.query("SELECT * FROM components WHERE id=?").get(id) as any;return c?layout(user,"Edit component",`<h1>Edit component</h1><div class="card"><form method="post" action="/components/${id}">${form(c)}<button class="btn">Save</button></form></div>`,"/components"):layout(user,"Not found","<h1>Not found</h1>");}
export async function update(user:User,id:string,req:Request):Promise<Response>{const v=await formVals(req);const used=(db.query("SELECT COALESCE(SUM(qty),0) n FROM component_assets WHERE component_id=?").get(id) as any).n;const x=vals(v);x[2]=Math.max(used,x[2]);db.run("UPDATE components SET name=?,category_id=?,qty=?,min_qty=?,location_id=?,cost=?,serial=?,notes=? WHERE id=?",[...x,id]);logActivity(user.id,"update","component",Number(id),v("name"));return redirect(`/components/${id}?m=Saved`);}
export function removeEntity(user:User,id:string):Response{const c=db.query("SELECT name FROM components WHERE id=?").get(id) as any;db.run("DELETE FROM components WHERE id=?",[id]);logActivity(user.id,"delete","component",Number(id),c?.name||"");return redirect("/components?m=Deleted");}
export async function install(user:User,id:string,req:Request):Promise<Response>{const v=await formVals(req);const qty=Math.max(1,Number(v("qty"))||1);let ok=false;db.transaction(()=>{const c=db.query("SELECT qty-COALESCE((SELECT SUM(qty) FROM component_assets WHERE component_id=?),0) available FROM components WHERE id=?").get(id,id) as any;const a=db.query("SELECT asset_tag FROM assets WHERE id=?").get(v("asset_id")) as any;if(!c||c.available<qty||!a)return;db.run("INSERT INTO component_assets(component_id,asset_id,qty) VALUES(?,?,?) ON CONFLICT(component_id,asset_id) DO UPDATE SET qty=qty+excluded.qty,at=datetime('now')",[id,v("asset_id"),qty]);logActivity(user.id,"install","component",Number(id),`${qty} into ${a.asset_tag}`);ok=true;})();return redirect(`/components/${id}?m=${encodeURIComponent(ok?"Installed":"Insufficient stock")}`);}
export async function removeInstall(user:User,id:string,rowId:string,req:Request):Promise<Response>{const v=await formVals(req);const qty=Math.max(1,Number(v("qty"))||1);const x=db.query("SELECT x.qty,a.asset_tag FROM component_assets x JOIN assets a ON a.id=x.asset_id WHERE x.id=? AND x.component_id=?").get(rowId,id) as any;if(x){if(qty>=x.qty)db.run("DELETE FROM component_assets WHERE id=?",[rowId]);else db.run("UPDATE component_assets SET qty=qty-? WHERE id=?",[qty,rowId]);logActivity(user.id,"remove","component",Number(id),`${Math.min(qty,x.qty)} from ${x.asset_tag}`);}return redirect(`/components/${id}?m=Removed`);}

export function assetInstalled(assetId:string):any[]{return db.query("SELECT c.id,c.name,x.qty,x.at FROM component_assets x JOIN components c ON c.id=x.component_id WHERE x.asset_id=? ORDER BY c.name").all(assetId) as any[];}
export const componentImportPage=(user:User,url:URL)=>inventoryImportPage(user,url,importConfig);
export const componentImportTemplate=()=>inventoryImportTemplate(importConfig);
export const componentImport=(user:User,req:Request)=>inventoryImport(user,req,importConfig);
