import { db,logActivity } from "./db";
import type { User } from "./auth";
import { esc,formVals,layout,opt,redirect } from "./web";

function form(d:any={}):string{const users=db.query("SELECT id,name FROM users WHERE active=1 ORDER BY name").all() as any[];return `<div class="frm"><div><label>Name *</label><input name="name" value="${esc(d.name||"")}" required></div><div><label>Manager</label><select name="manager_id"><option value="">—</option>${opt(users,d.manager_id)}</select></div></div>`;}
export function list(user:User,url:URL):Response{const rows=db.query(`SELECT d.*,u.name manager,(SELECT COUNT(*) FROM users x WHERE x.department_id=d.id) users FROM departments d LEFT JOIN users u ON u.id=d.manager_id ORDER BY d.name`).all() as any[];return layout(user,"Departments",`<h1>Departments</h1><div class="toolbar"><a class="btn" href="/departments/new">+ New department</a></div><div class="card table-wrap" style="padding:0"><table class="sticky-table"><tr><th>Name</th><th>Manager</th><th>Users</th><th></th></tr>${rows.map(d=>`<tr><td>${esc(d.name)}</td><td>${esc(d.manager||"")}</td><td>${d.users}</td><td><a class="btn sec sm" href="/departments/${d.id}/edit">Edit</a> <form class="inline" method="post" action="/departments/${d.id}/delete"><button class="btn danger sm">Delete</button></form></td></tr>`).join("")}</table></div>`,"/departments",url.searchParams.get("m")||"");}
export function newPage(user:User):Response{return layout(user,"New department",`<h1>New department</h1><div class="card"><form method="post" action="/departments">${form()}<button class="btn">Create</button></form></div>`,"/departments");}
export async function create(user:User,req:Request):Promise<Response>{const v=await formVals(req);if(!v("name"))return redirect("/departments/new?m=Name is required");try{const r=db.run("INSERT INTO departments(name,manager_id) VALUES(?,?)",[v("name"),v("manager_id")||null]);logActivity(user.id,"create","department",Number(r.lastInsertRowid),v("name"));return redirect("/departments?m=Department created");}catch(e:any){return redirect(`/departments?m=${encodeURIComponent(`Error: ${e.message}`)}`);}}
export function editPage(user:User,id:string):Response{const d=db.query("SELECT * FROM departments WHERE id=?").get(id) as any;return d?layout(user,"Edit department",`<h1>Edit department</h1><div class="card"><form method="post" action="/departments/${esc(id)}/edit">${form(d)}<button class="btn">Save</button></form></div>`,"/departments"):layout(user,"Not found","<h1>Department not found</h1>","/departments");}
export async function update(user:User,id:string,req:Request):Promise<Response>{const v=await formVals(req);if(!v("name"))return redirect(`/departments/${encodeURIComponent(id)}/edit?m=Name is required`);db.run("UPDATE departments SET name=?,manager_id=? WHERE id=?",[v("name"),v("manager_id")||null,id]);logActivity(user.id,"update","department",Number(id),v("name"));return redirect("/departments?m=Department saved");}
export function remove(user:User,id:string):Response{const d=db.query("SELECT name FROM departments WHERE id=?").get(id) as any;if(d){db.run("DELETE FROM departments WHERE id=?",[id]);logActivity(user.id,"delete","department",Number(id),d.name);}return redirect("/departments?m=Department deleted");}
